$(function(){
    $('.nav-link.hoverable').hover(
        function(){
            $(this).addClass('bounce');
        },
        function(){
            $(this).removeClass('bounce');
        }
    );
});